@startuml Manage Restaurant (POST)

header Sameple CappuGaewNung Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Restaurant (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:restaurants" as routerRestaurants
participant "<<middleware>>\n:auth" as middleware
participant "<<controllers>>\n:restaurants" as controllersRestaurants
participant "<<model>>\n:Restaurant" as modelRestaurant
database "<<MongoDB>>\n:restaurants" as RestaurantsDatabase

client->server ++:req.post('/restaurants')
server->routerRestaurants ++:app.use('/restaurants',restaurants)
routerRestaurants->middleware ++:protect(req, res, next)
middleware->middleware ++:authorize("admin")(req, res, next)

alt User is admin
    middleware->controllersRestaurants ++:createRestaurant()
    controllersRestaurants->modelRestaurant ++:create(req.body)
    modelRestaurant ->RestaurantsDatabase ++: RestaurantSchema
    RestaurantsDatabase --> modelRestaurant --: restaurant
    controllersRestaurants <-- modelRestaurant --:restaurant
    controllersRestaurants->client --:response
else User is not admin
    middleware->client --:response
    end


@enduml
